source: .
destination: ./_site
includes: ./_includes
url: "https://vallandingham.me"

permalink: /:title.html

#base_url: http://vlandham.com
#base_url: /
description: ""

encoding: utf-8

defaults:
  - scope:
      path: ""
    values:
      ogtype: "website"
  - scope:
      path: ""
      type: "posts"
    values:
      ogtype: "article"
